### ISSUE TITLE
the sprites seem to be very broken

### ISSUE THREAD

**Issue by hbuddz** [Jasmarkelina/Tantros-Mod#16]
![image](https://user-images.githubusercontent.com/79516671/202325441-3055ace1-eb66-4516-83dd-a18436045bf5.png)

**Comment by Plastel** [comment]
Hi, Here Plastel from tantros mod, it seems like the broken sprites seem to be because they have no texture for now, meanwhile you could try my fork, that has more sprites (Plastel/Tantros-mod), Could you install my fork and send me a picture of the mod content?, Thanks.

**Comment by hbuddz** [comment]
still just as broken
![image](https://user-images.githubusercontent.com/79516671/202333833-ce746257-2ef6-4a29-9f84-2dfa91672081.png)

**Comment by Plastel** [comment]
the count of broken sprites had reduced, that means that the broken sprites, actually have no texture yet, good afternoon, morning or night.

**Comment by Jasmarkelina** [comment]
frog
