### ISSUE TITLE
Lighter gray shade

### ISSUE THREAD

**Issue by GitHubUser-B** [Jasmarkelina/Tantros-Mod#26]
Not a problem with the mod, just a suggestion. Because erekir structures have a darker gray shade than serpulo, and erekir is a "fire themed" planet, why not make tantros structures lighter than serpulo ones since it is a "water themed" planet? Just something that would be cool

**Comment by Jasmarkelina** [comment]
Good idea, that'd make it a little better to see the blocks at a tantrian night!
