### ISSUE TITLE
Wreck target calculation is wrong

### ISSUE THREAD

**Issue by Hessi9** [Jasmarkelina/Tantros-Mod#29]
The Wreck target calculation calculates the target point according to the movement speed of the enemy and the initial speed of the torpedo. As the torpedo increases speed the calculated target point is always wrong and nearly always torpedos miss the target.

**Comment by Plastel** [comment]
we should make wreck bullet faster but without that nasty acceleration

**Comment by Plastel** [comment]
Gonna make it on my fork

**Comment by Plastel** [comment]
Try it out now, Basilisk should also work
