### ISSUE TITLE
Items resources from the mod able to enter junction. but is unable to exit

### ISSUE THREAD

**Issue by Mac33299** [Jasmarkelina/Tantros-Mod#34]
![Screenshot (4013)](https://user-images.githubusercontent.com/110599229/216551847-ea1f34dc-986b-43dd-b39c-c339637dd4e8.png)

**Comment by Jasmarkelina** [comment]
hmm... I'll try to figure this one out, apologies if I kept this issue on hold...

**Comment by Jasmarkelina** [comment]
ok, I tried it on my latest version of the mod... It doesn't seem to be doing it, not sure why...
