### ISSUE TITLE
It just sends the wrong core and softlocks you

### ISSUE THREAD

**Issue by UrbanGoose02** [Jasmarkelina/Tantros-Mod#35]
If you lose a sector and launch again it somehow both saves previous progress on said sector and launches the Shard core intead of the Ruin core, which, if you haven't built automatic mining yet straight up softlocks you, as Alpha cannot manually mine the mod's unique ores. Even if you did set up mining beforehand, the Shard core is extremely weak, making it hard to defend against the mod's persistent and annoying units.

**Comment by Jasmarkelina** [comment]
ah, apologies for keeping you on hold for the 3 1/2 months
but we are trying to figure out why the default core just sets to "null" when we assign it to Tantros, for now, we've intentionally made a typo in the main javascript code.

**Comment by Jasmarkelina** [comment]
It is fixed. I finally figured it out, you can check it out in the releases tags
